version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_DB: appflaskpydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d appflaskpydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  webapp:
    build: .
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

